pipeline {
    // 1. Set global agent to 'any' instead of 'none'
    agent any 

    environment {
        REGISTRY = 'localhost:5001'
        IMAGE    = 'calculator'
        TAG      = "${BUILD_NUMBER}"
        TOPIC    = 'tickets'
        BROKER   = 'week9-kafka:29092' 
    }
    stages {
        stage('Checkout code') {
            steps { 
                git url: 'https://github.com/nalkiliddar/umlSU26', branch: 'main'
                sh """
                cd week9
                """
            }
        }
        stage('Build & push image') {
            steps {
                sh '''
                    docker build -t ${REGISTRY}/${IMAGE}:${TAG} week9/app
                    docker push ${REGISTRY}/${IMAGE}:${TAG}
                '''
            }
        }
        stage('Announce to Kafka') {
            // 2. Overriding agent specifically for this containerized task
            agent {
                docker {
                    image 'localhost:5001/kafka-python:1'
                    args '--network week9_default'
                }
            }
            steps {
                // 3. Explicitly pass variables into the container environment
                withEnv(["BROKER=${BROKER}", "TOPIC=${TOPIC}"]) {
                    sh 'python week9/publish_event.py'
                }
            }
        }
    }
}
